databases:
  - name: postgresdb
    plan: free
    databaseName: alxsocialmediaapi
    user: postgres

services:
  - type: web
    plan: free
    name: alxsocialmediaapi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn alxsocialmediaapi.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4